/** Named places the app can open a plan from. Dimensions stay on VenuePreset. */
import type { TkuPlace } from "./tkuCampus";

const CLASSROOM = "venue:tku-classroom";
const RECT = "venue:rect-classroom";
const E310 = "venue:tku-e310";
const BOOTH = "venue:tku-booth";

export const TKU_PLACES: TkuPlace[] = [
  { id: "E308", campusId: "tamsui", buildingCode: "E", floor: 3, room: "08", name: "E308 工學大樓教室", kind: "classroom", venuePresetId: CLASSROOM, aliases: ["E308"], clubUse: "primary", mentionCount: 101, note: "禪學社文件提及最多的教室。套用淡江教室起點，長寬待現場校正。" },
  { id: "E310", campusId: "tamsui", buildingCode: "E", floor: 3, room: "10", name: "E310 工學大樓教室", kind: "classroom", venuePresetId: E310, aliases: ["E310"], clubUse: "frequent", mentionCount: 54, note: "Golden Venue。長寬仍未實測。" },
  { id: "E301", campusId: "tamsui", buildingCode: "E", floor: 3, room: "01", name: "E301 工學大樓教室", kind: "classroom", venuePresetId: CLASSROOM, clubUse: "fallback", mentionCount: 4, note: "偶用。" },
  { id: "E311", campusId: "tamsui", buildingCode: "E", floor: 3, room: "11", name: "E311 工學大樓教室", kind: "classroom", venuePresetId: CLASSROOM, clubUse: "fallback", mentionCount: 4, note: "偶用。" },
  { id: "E680", campusId: "tamsui", buildingCode: "E", floor: 6, room: "80", name: "E680 會議室", kind: "hall", venuePresetId: RECT, aliases: ["E680"], clubUse: "fallback", publishedCapacity: 44, note: "114 外借表 44 人。" },
  { id: "SG109", campusId: "tamsui", buildingCode: "SG", floor: 1, room: "09", name: "SG109 社辦", kind: "office", venuePresetId: CLASSROOM, aliases: ["社辦", "SG109"], clubUse: "office", mentionCount: 100, note: "集合／搬巧拼起點。套用淡江教室起點，不是實測社辦平面。" },
  { id: "SG320", campusId: "tamsui", buildingCode: "SG", floor: 3, room: "20", name: "SG320 體育館教室", kind: "classroom", venuePresetId: CLASSROOM, aliases: ["SG320"], clubUse: "frequent", mentionCount: 27, note: "體育館教室。套用淡江教室起點。" },
  { id: "SG319", campusId: "tamsui", buildingCode: "SG", floor: 3, room: "19", name: "SG319 體育館教室", kind: "classroom", venuePresetId: CLASSROOM, clubUse: "fallback", mentionCount: 4, note: "偶用。" },
  { id: "SG321", campusId: "tamsui", buildingCode: "SG", floor: 3, room: "21", name: "SG321 體育館教室", kind: "classroom", venuePresetId: CLASSROOM, clubUse: "fallback", mentionCount: 4, note: "偶用。" },
  { id: "SG402", campusId: "tamsui", buildingCode: "SG", floor: 4, room: "02", name: "SG402 體育館教室", kind: "classroom", venuePresetId: CLASSROOM, clubUse: "fallback", mentionCount: 13, note: "偶用。" },
  { id: "SG603", campusId: "tamsui", buildingCode: "SG", floor: 6, room: "03", name: "SG603 體育館教室", kind: "classroom", venuePresetId: CLASSROOM, clubUse: "fallback", mentionCount: 4, note: "偶用。" },
  { id: "scroll-plaza", campusId: "tamsui", buildingCode: "T", name: "書卷廣場", kind: "plaza", venuePresetId: BOOTH, aliases: ["書卷廣場", "蛋捲廣場"], clubUse: "outdoor", note: "驚聲大樓前。套用 3×3 帳篷起點。" },
  { id: "tongzhou-plaza", campusId: "tamsui", buildingCode: "I", floor: 1, name: "同舟廣場", kind: "plaza", venuePresetId: BOOTH, aliases: ["同舟廣場", "HC1"], clubUse: "outdoor", note: "綜大 1F 中庭。外借表列有場地維護費，面積未當成長寬。" },
  { id: "hc-hall", campusId: "tamsui", buildingCode: "HC", name: "守謙國際會議中心", kind: "hall", venuePresetId: RECT, aliases: ["守謙"], clubUse: "fallback", note: "大型會議大樓入口。分廳見 HC 室號。" },
  { id: "HC310", campusId: "tamsui", buildingCode: "HC", floor: 3, room: "10", name: "HC310 有蓮國際會議廳", kind: "hall", venuePresetId: RECT, aliases: ["有蓮", "有蓮國際會議廳", "HC310"], clubUse: "fallback", publishedCapacity: 350, note: "114 外借表 350 人。不得用餐。" },
  { id: "HC102", campusId: "tamsui", buildingCode: "HC", floor: 1, room: "02", name: "HC102 馬來西亞校友廳", kind: "hall", venuePresetId: RECT, aliases: ["HC102"], clubUse: "fallback", publishedCapacity: 22, note: "114 外借表 22 人。" },
  { id: "HC103", campusId: "tamsui", buildingCode: "HC", floor: 1, room: "03", name: "HC103 雙鴻廳", kind: "hall", venuePresetId: RECT, aliases: ["HC103"], clubUse: "fallback", publishedCapacity: 24, note: "114 外借表 24 人。" },
  { id: "HC104", campusId: "tamsui", buildingCode: "HC", floor: 1, room: "04", name: "HC104 現代保險廳", kind: "hall", venuePresetId: RECT, aliases: ["HC104"], clubUse: "fallback", note: "守謙中型會議室。容納人數未列入公開表。" },
  { id: "HC105", campusId: "tamsui", buildingCode: "HC", floor: 1, room: "05", name: "HC105 承運廳", kind: "hall", venuePresetId: RECT, aliases: ["HC105"], clubUse: "fallback", note: "守謙中型會議室。" },
  { id: "HC106", campusId: "tamsui", buildingCode: "HC", floor: 1, room: "06", name: "HC106 伯馬廳", kind: "hall", venuePresetId: RECT, aliases: ["HC106"], clubUse: "fallback", note: "守謙中型會議室。" },
  { id: "HC107", campusId: "tamsui", buildingCode: "HC", floor: 1, room: "07", name: "HC107 黃憲堂教授紀念廳", kind: "hall", venuePresetId: RECT, aliases: ["HC107"], clubUse: "fallback", note: "守謙中型會議室。" },
  { id: "HC303", campusId: "tamsui", buildingCode: "HC", floor: 3, room: "03", name: "HC303 文甫廳", kind: "hall", venuePresetId: RECT, aliases: ["HC303"], clubUse: "fallback", note: "守謙會議室。" },
  { id: "HC305", campusId: "tamsui", buildingCode: "HC", floor: 3, room: "05", name: "HC305 世界校友會正大廳", kind: "hall", venuePresetId: RECT, aliases: ["HC305"], clubUse: "fallback", note: "守謙會議室。" },
  { id: "HC306", campusId: "tamsui", buildingCode: "HC", floor: 3, room: "06", name: "HC306 永光廳", kind: "hall", venuePresetId: RECT, aliases: ["HC306"], clubUse: "fallback", note: "守謙會議室。" },
  { id: "HC307", campusId: "tamsui", buildingCode: "HC", floor: 3, room: "07", name: "HC307 穩懋廳", kind: "hall", venuePresetId: RECT, aliases: ["HC307"], clubUse: "fallback", note: "守謙會議室。" },
  { id: "HC309", campusId: "tamsui", buildingCode: "HC", floor: 3, room: "09", name: "HC309 貴賓室", kind: "hall", venuePresetId: RECT, aliases: ["HC309"], clubUse: "fallback", note: "守謙貴賓室。" },
  { id: "HC401", campusId: "tamsui", buildingCode: "HC", floor: 4, room: "01", name: "HC401 傑克廳", kind: "hall", venuePresetId: RECT, aliases: ["HC401"], clubUse: "fallback", note: "守謙會議室。" },
  { id: "HC403", campusId: "tamsui", buildingCode: "HC", floor: 4, room: "03", name: "HC403 科葉廳", kind: "hall", venuePresetId: RECT, aliases: ["HC403"], clubUse: "fallback", note: "守謙會議室。" },
  { id: "HC405", campusId: "tamsui", buildingCode: "HC", floor: 4, room: "05", name: "HC405 郝俠遂教授紀念廳", kind: "hall", venuePresetId: RECT, aliases: ["HC405"], clubUse: "fallback", note: "守謙會議室。" },
  { id: "HC406", campusId: "tamsui", buildingCode: "HC", floor: 4, room: "06", name: "HC406 宗瑋義蓮紀念廳", kind: "hall", venuePresetId: RECT, aliases: ["HC406"], clubUse: "fallback", note: "守謙會議室。" },
  { id: "hc2-gallery", campusId: "tamsui", buildingCode: "HC", floor: 2, name: "守謙 HC2 展示廳", kind: "hall", venuePresetId: RECT, aliases: ["HC2"], clubUse: "fallback", note: "外借系統活動場地。尺寸未實測。" },
  { id: "hc5-terrace", campusId: "tamsui", buildingCode: "HC", floor: 5, name: "守謙 HC5 頂樓露台", kind: "outdoor", venuePresetId: BOOTH, aliases: ["HC5"], clubUse: "outdoor", note: "外借系統活動場地。套用戶外攤位起點。" },
  { id: "palace-classroom", campusId: "tamsui", buildingCode: "H", name: "宮燈教室", kind: "classroom", venuePresetId: CLASSROOM, aliases: ["宮燈"], clubUse: "fallback", note: "1954 古跡教室。" },
  { id: "palace-avenue", campusId: "tamsui", buildingCode: "H", name: "宮燈大道", kind: "outdoor", venuePresetId: BOOTH, aliases: ["宮燈大道", "宮燈道", "情人道", "宮燈步道"], clubUse: "outdoor", note: "外借系統戶外活動場地。宮燈教室中間步道。" },
  { id: "chueh-hsuan-garden", campusId: "tamsui", buildingCode: "CH", name: "覺軒花園", kind: "outdoor", venuePresetId: BOOTH, aliases: ["覺軒花園"], clubUse: "outdoor", note: "戶外茶會起點。" },
  { id: "library", campusId: "tamsui", buildingCode: "U", name: "覺生紀念圖書館", kind: "hall", venuePresetId: RECT, aliases: ["圖書館", "總館"], clubUse: "fallback", note: "九層總館。" },
  { id: "maritime-museum", campusId: "tamsui", buildingCode: "M", name: "海事博物館", kind: "hall", venuePresetId: RECT, aliases: ["海博"], clubUse: "fallback", note: "免費開放。" },
  { id: "history-museum", campusId: "tamsui", buildingCode: "TH", name: "校史館暨張建邦創辦人紀念館", kind: "hall", venuePresetId: RECT, aliases: ["校史館"], clubUse: "fallback", note: "舊瀛苑整修。" },
  { id: "activity-center", campusId: "tamsui", buildingCode: "R", name: "學生活動中心", kind: "hall", venuePresetId: RECT, aliases: ["活動中心"], clubUse: "fallback", note: "社團空間。" },
  { id: "sa-center", campusId: "lanyang", buildingCode: "SA", name: "紹\u8b03紀念活動中心", kind: "hall", venuePresetId: RECT, aliases: ["紹\u8b03活動中心", "紹謨活動中心", "紹謃紀念活動中心", "紹謃活動中心"], clubUse: "fallback", note: "蘭陽，不是淡水 SG。" },
  { id: "sg7-hall", campusId: "tamsui", buildingCode: "SG", floor: 7, name: "SG7 體育館集會場", kind: "hall", venuePresetId: RECT, aliases: ["SG7"], clubUse: "fallback", note: "7F 集會場。" },
  { id: "sg4-court", campusId: "tamsui", buildingCode: "SG", floor: 4, name: "SG4 羽球／排球場", kind: "hall", venuePresetId: RECT, aliases: ["SG4"], clubUse: "fallback", note: "4F 球場。" },
  { id: "sg-judo", campusId: "tamsui", buildingCode: "SG", floor: 0, name: "SG B1 柔道／武術室", kind: "hall", venuePresetId: RECT, aliases: ["柔道室", "武術室"], clubUse: "fallback", publishedCapacity: 100, note: "淡水外借表柔道／武術室 100 人。長寬未實測。" },
  { id: "sg-dance", campusId: "tamsui", buildingCode: "SG", name: "SG 舞蹈室", kind: "hall", venuePresetId: RECT, aliases: ["舞蹈室"], clubUse: "fallback", publishedCapacity: 100, note: "淡水外借表舞蹈室 100 人。樓層待現場確認。" },
  { id: "sg-table-tennis", campusId: "tamsui", buildingCode: "SG", floor: 3, name: "SG 桌球室", kind: "hall", venuePresetId: RECT, aliases: ["桌球室"], clubUse: "fallback", publishedCapacity: 100, note: "淡水外借表桌球室 100 人。3F 公開用途含桌球。" },
  { id: "pool", campusId: "tamsui", buildingCode: "N", name: "游泳池", kind: "hall", venuePresetId: RECT, aliases: ["游泳池"], clubUse: "fallback", publishedCapacity: 200, note: "淡水外借表游泳池 200 人。與「游泳館」館舍不同層；長寬未實測。" },
  { id: "black-swan", campusId: "tamsui", name: "黑天鵝展示廳", kind: "hall", venuePresetId: RECT, aliases: ["黑天鵝"], clubUse: "fallback", publishedCapacity: 80, note: "外借表 80 人。" },
  { id: "ching-sheng-hall", campusId: "tamsui", buildingCode: "T", name: "驚聲國際會議廳", kind: "hall", venuePresetId: RECT, aliases: ["驚聲國際會議廳", "驚聲國際廳"], clubUse: "fallback", publishedCapacity: 175, note: "114 外借表 175 人。" },
  { id: "knan-slope", campusId: "tamsui", name: "克難坡", kind: "outdoor", venuePresetId: BOOTH, aliases: ["克難坡"], clubUse: "outdoor", note: "132 階，1953。" },
  { id: "ching-sheng-statue", campusId: "tamsui", buildingCode: "N", name: "驚聲銅像廣場", kind: "plaza", venuePresetId: BOOTH, aliases: ["驚聲銅像"], clubUse: "outdoor", note: "游泳館前方。" },
  { id: "fortune-garden", campusId: "tamsui", buildingCode: "B", name: "福園", kind: "outdoor", venuePresetId: BOOTH, aliases: ["福園"], clubUse: "outdoor", note: "商管大樓前。" },
  { id: "li-shuang-ze", campusId: "tamsui", name: "李雙澤紀念碑", kind: "outdoor", venuePresetId: BOOTH, aliases: ["李雙澤"], clubUse: "outdoor", note: "民歌紀念地。" },
  { id: "sheep-lawn", campusId: "tamsui", name: "牧羊草坪", kind: "outdoor", venuePresetId: BOOTH, aliases: ["牧羊草坪"], clubUse: "outdoor", note: "休閒草坪。外借系統寫牧羊及陽光草坪。" },
  { id: "sun-lawn", campusId: "tamsui", name: "陽光草坪", kind: "outdoor", venuePresetId: BOOTH, aliases: ["陽光草坪"], clubUse: "outdoor", note: "外借系統戶外活動場地。" },
  { id: "water-dance-plaza", campusId: "tamsui", name: "水舞廣場", kind: "plaza", venuePresetId: BOOTH, aliases: ["水舞廣場"], clubUse: "outdoor", note: "外借系統戶外活動場地。" },
  { id: "pedestrian-zone", campusId: "tamsui", name: "行人徒步區", kind: "outdoor", venuePresetId: BOOTH, aliases: ["行人徒步區"], clubUse: "outdoor", note: "外借系統戶外活動場地。" },
  { id: "dolphin-milestone", campusId: "tamsui", name: "海豚吉祥物里程碑", kind: "outdoor", venuePresetId: BOOTH, aliases: ["淡江海豚"], clubUse: "outdoor", note: "吉祥物地標。" },
  { id: "food-plaza", campusId: "tamsui", name: "美食廣場", kind: "outdoor", venuePresetId: BOOTH, aliases: ["美食廣場"], clubUse: "outdoor", note: "臨時攤位區。共筆代號 Z2100。" },
  { id: "five-tiger-stele", campusId: "tamsui", buildingCode: "X", name: "五虎碑", kind: "outdoor", venuePresetId: BOOTH, aliases: ["五虎碑", "五虎碑廣場"], clubUse: "outdoor", note: "五虎崗地標。" },
  { id: "lanyang-hall", campusId: "lanyang", buildingCode: "LH", name: "建邦國際會議廳", kind: "hall", venuePresetId: RECT, aliases: ["建邦國際廳", "強邦國際會議廳"], clubUse: "fallback", publishedCapacity: 286, note: "外借表 286 人。舊文偶作「強邦」。" },
  { id: "CL302", campusId: "lanyang", buildingCode: "CL", floor: 3, room: "02", name: "CL302 語練教室", kind: "classroom", venuePresetId: RECT, aliases: ["CL302"], clubUse: "fallback", publishedCapacity: 64, note: "蘭陽 114 外借表語練教室 64 人。" },
  { id: "CL304", campusId: "lanyang", buildingCode: "CL", floor: 3, room: "04", name: "CL304 會議室", kind: "hall", venuePresetId: RECT, aliases: ["CL304"], clubUse: "fallback", publishedCapacity: 18, note: "蘭陽 114 外借表 18 人。" },
  { id: "CL318", campusId: "lanyang", buildingCode: "CL", floor: 3, room: "18", name: "CL318 會議室", kind: "hall", venuePresetId: RECT, aliases: ["CL318"], clubUse: "fallback", publishedCapacity: 18, note: "蘭陽 114 外借表 18 人。" },
  { id: "CL324", campusId: "lanyang", buildingCode: "CL", floor: 3, room: "24", name: "CL324 電腦教室", kind: "classroom", venuePresetId: RECT, aliases: ["CL324"], clubUse: "fallback", publishedCapacity: 60, note: "蘭陽 114 外借表電腦教室 60 人。" },
  { id: "CL408", campusId: "lanyang", buildingCode: "CL", floor: 4, room: "08", name: "CL408 會議室", kind: "hall", venuePresetId: RECT, aliases: ["CL408"], clubUse: "fallback", note: "蘭陽外借表。公開容納人數未列入 114 會議室欄。" },
  { id: "CL423", campusId: "lanyang", buildingCode: "CL", floor: 4, room: "23", name: "CL423 會議室", kind: "hall", venuePresetId: RECT, aliases: ["CL423"], clubUse: "fallback", publishedCapacity: 16, note: "蘭陽 114 外借表 16 人。" },
  { id: "CL426", campusId: "lanyang", buildingCode: "CL", floor: 4, room: "26", name: "CL426 會議室", kind: "hall", venuePresetId: RECT, aliases: ["CL426"], clubUse: "fallback", note: "蘭陽外借表。公開容納人數未列入 114 會議室欄。" },
  { id: "CL439", campusId: "lanyang", buildingCode: "CL", floor: 4, room: "39", name: "CL439 教室", kind: "classroom", venuePresetId: RECT, aliases: ["CL439"], clubUse: "fallback", publishedCapacity: 100, note: "蘭陽 114 外借表 100 人。" },
  { id: "CL504", campusId: "lanyang", buildingCode: "CL", floor: 5, room: "04", name: "CL504 教室", kind: "classroom", venuePresetId: RECT, aliases: ["CL504"], clubUse: "fallback", publishedCapacity: 18, note: "蘭陽 114 外借表 18 人。" },
  { id: "CL506", campusId: "lanyang", buildingCode: "CL", floor: 5, room: "06", name: "CL506 會議室", kind: "hall", venuePresetId: RECT, aliases: ["CL506"], clubUse: "fallback", publishedCapacity: 32, note: "蘭陽 114 外借表 32 人。" },
  { id: "lanyang-courts", campusId: "lanyang", name: "蘭陽室外球場", kind: "outdoor", venuePresetId: BOOTH, aliases: ["蘭陽籃球場", "蘭陽網球場", "蘭陽排球場"], clubUse: "outdoor", publishedCapacity: 100, note: "蘭陽 114 外借表室外籃球／網球／排球場 100 人。不是實測場地尺寸。" },
  { id: "lanyang-track", campusId: "lanyang", name: "蘭陽室外 PU 跑道", kind: "outdoor", venuePresetId: BOOTH, aliases: ["蘭陽跑道"], clubUse: "outdoor", publishedCapacity: 100, note: "蘭陽 114 外借表室外 PU 跑道 100 人。" },
  { id: "lanyang-lookout", campusId: "lanyang", name: "蘭陽戶外觀景平台", kind: "outdoor", venuePresetId: BOOTH, aliases: ["戶外觀景平台"], clubUse: "outdoor", publishedCapacity: 100, note: "蘭陽 114 外借表戶外觀景平台公共區域 100 人。" },
  { id: "lanyang-billiards", campusId: "lanyang", name: "蘭陽撞球室", kind: "hall", venuePresetId: RECT, aliases: ["撞球室"], clubUse: "fallback", publishedCapacity: 60, note: "蘭陽 114 外借表撞球室 60 人。" },
  { id: "D206", campusId: "taipei", buildingCode: "D", floor: 2, room: "06", name: "D206 中正紀念堂", kind: "hall", venuePresetId: RECT, aliases: ["D206", "中正紀念堂"], publishedCapacity: 217, note: "外借表 217 人。" },
  { id: "D207", campusId: "taipei", buildingCode: "D", floor: 2, room: "07", name: "D207 階梯教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 120, note: "外借表 120 人。" },
  { id: "D208", campusId: "taipei", buildingCode: "D", floor: 2, room: "08", name: "D208 階梯教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 120, note: "外借表 120 人。" },
  { id: "D211", campusId: "taipei", buildingCode: "D", floor: 2, room: "11", name: "D211 多媒體教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 81, note: "外借表 81 人。" },
  { id: "D214", campusId: "taipei", buildingCode: "D", floor: 2, room: "14", name: "D214 會議室", kind: "hall", venuePresetId: RECT, aliases: ["D214"], publishedCapacity: 21, note: "外借表 21 人。" },
  { id: "D304", campusId: "taipei", buildingCode: "D", floor: 3, room: "04", name: "D304 電腦教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 48, note: "外借表 48 人。" },
  { id: "D305", campusId: "taipei", buildingCode: "D", floor: 3, room: "05", name: "D305 電腦教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 46, note: "外借表 46 人。" },
  { id: "D309", campusId: "taipei", buildingCode: "D", floor: 3, room: "09", name: "D309 個案教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 54, note: "外借表 54 人。" },
  { id: "D310", campusId: "taipei", buildingCode: "D", floor: 3, room: "10", name: "D310 個案教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 50, note: "外借表 50 人。" },
  { id: "D318", campusId: "taipei", buildingCode: "D", floor: 3, room: "18", name: "D318 多媒體教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 81, note: "外借表 81 人。" },
  { id: "D321", campusId: "taipei", buildingCode: "D", floor: 3, room: "21", name: "D321 多媒體教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 16, note: "外借表 D321–D323 16 人。" },
  { id: "D322", campusId: "taipei", buildingCode: "D", floor: 3, room: "22", name: "D322 多媒體教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 16, note: "外借表 D321–D323 16 人。" },
  { id: "D323", campusId: "taipei", buildingCode: "D", floor: 3, room: "23", name: "D323 多媒體教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 16, note: "外借表 D321–D323 16 人。" },
  { id: "D401", campusId: "taipei", buildingCode: "D", floor: 4, room: "01", name: "D401 多媒體教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 90, note: "外借表 90 人。" },
  { id: "D408", campusId: "taipei", buildingCode: "D", floor: 4, room: "08", name: "D408 多媒體教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 81, note: "外借表 81 人。" },
  { id: "D501", campusId: "taipei", buildingCode: "D", floor: 5, room: "01", name: "D501 多媒體教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 90, note: "外借表 90 人。" },
  { id: "D507", campusId: "taipei", buildingCode: "D", floor: 5, room: "07", name: "D507 校友聯誼會館會議室", kind: "hall", venuePresetId: RECT, aliases: ["D507"], publishedCapacity: 60, note: "外借表 60 人。" },
  { id: "D508", campusId: "taipei", buildingCode: "D", floor: 5, room: "08", name: "D508 校友聯誼會館會議室", kind: "hall", venuePresetId: RECT, aliases: ["D508"], publishedCapacity: 60, note: "外借表 60 人。" },
  { id: "D509", campusId: "taipei", buildingCode: "D", floor: 5, room: "09", name: "D509 會議室", kind: "hall", venuePresetId: RECT, publishedCapacity: 60, note: "臺北外借表與 D508 同列校友聯誼會館 60 人。" },
  { id: "D510", campusId: "taipei", buildingCode: "D", floor: 5, room: "10", name: "D510 個案教室", kind: "classroom", venuePresetId: RECT, publishedCapacity: 50, note: "外借表 50 人。" },
  { id: "reviewing-stand", campusId: "tamsui", buildingCode: "P", name: "操場司令臺", kind: "outdoor", venuePresetId: BOOTH, aliases: ["司令臺", "操場"], clubUse: "outdoor", note: "操場集合。" },
  { id: "blue-white-town", campusId: "tamsui", buildingCode: "GB", name: "藍白小鎮", kind: "outdoor", venuePresetId: BOOTH, aliases: ["藍白小鎮"], clubUse: "outdoor", note: "餐飲休閒區。" },
  { id: "wuhugang-court", campusId: "tamsui", buildingCode: "XC", name: "五虎崗綜合球場", kind: "outdoor", venuePresetId: BOOTH, aliases: ["綜合球場"], clubUse: "outdoor", note: "戶外球場。" },
  { id: "skating-rink", campusId: "tamsui", buildingCode: "SS", name: "溜冰場", kind: "outdoor", venuePresetId: BOOTH, aliases: ["溜冰場"], clubUse: "outdoor", note: "運動場地。尺寸未實測。" },
  { id: "tennis-court", campusId: "tamsui", buildingCode: "RT", name: "網球場", kind: "outdoor", venuePresetId: BOOTH, aliases: ["網球場"], clubUse: "outdoor", note: "運動場地。尺寸未實測。" },
  { id: "sung-tao", campusId: "tamsui", buildingCode: "Z", name: "松濤館／文\u932b藝術中心", kind: "hall", venuePresetId: RECT, aliases: ["松濤館", "文\u932b藝術中心", "文錙藝術中心", "文\u7e26藝術中心", "文縆藝術中心", "文\u9398藝術中心"], clubUse: "fallback", note: "展演空間。官方用字文\u932b。" },
  { id: "B302A", campusId: "tamsui", buildingCode: "B", floor: 3, room: "02A", name: "B302A 會議室", kind: "hall", venuePresetId: RECT, aliases: ["B302A"], clubUse: "fallback", publishedCapacity: 45, note: "114 外借表 45 人。" },
  { id: "S219", campusId: "tamsui", buildingCode: "S", floor: 2, room: "19", name: "S219 會議室", kind: "hall", venuePresetId: RECT, aliases: ["S219"], clubUse: "fallback", publishedCapacity: 12, note: "114 外借表 12 人。" },
  { id: "T306", campusId: "tamsui", buildingCode: "T", floor: 3, room: "06", name: "T306 會議室", kind: "hall", venuePresetId: RECT, aliases: ["T306"], clubUse: "fallback", publishedCapacity: 20, note: "114 外借表 20 人。" },
  { id: "C308", campusId: "tamsui", buildingCode: "C", floor: 3, room: "08", name: "C308 會議室", kind: "hall", venuePresetId: RECT, aliases: ["C308"], clubUse: "fallback", publishedCapacity: 25, note: "114 外借表 25 人。" },
  { id: "L522", campusId: "tamsui", buildingCode: "L", floor: 5, room: "22", name: "L522 會議室", kind: "hall", venuePresetId: RECT, aliases: ["L522"], clubUse: "fallback", publishedCapacity: 15, note: "114 外借表 15 人。" },
  { id: "chung-ling-zhongzheng", campusId: "tamsui", buildingCode: "C", name: "鍾靈中正堂", kind: "hall", venuePresetId: RECT, aliases: ["鍾靈中正堂", "中正堂"], clubUse: "fallback", publishedCapacity: 200, note: "外借表 200 人。在鍾靈化學館。" },
  { id: "b-generic", campusId: "tamsui", buildingCode: "B", name: "商管大樓教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["B 館"], clubUse: "fallback", note: "例如 B616。" },
  { id: "l-generic", campusId: "tamsui", buildingCode: "L", name: "文學館教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["L 館"], clubUse: "fallback", note: "例如 L201。" },
  { id: "fl-generic", campusId: "tamsui", buildingCode: "FL", name: "外語大樓教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["FL"], clubUse: "fallback", note: "FL + 樓層 + 室號。" },
  { id: "t-generic", campusId: "tamsui", buildingCode: "T", name: "驚聲大樓教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["T 館"], clubUse: "fallback", note: "書卷廣場在前。" },
  { id: "i-generic", campusId: "tamsui", buildingCode: "I", name: "綜大教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["I 館"], clubUse: "fallback", note: "同舟廣場在 1F。" },
  { id: "s-generic", campusId: "tamsui", buildingCode: "S", name: "科學館教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["科館"], clubUse: "fallback", note: "騮先紀念科學館。" },
  { id: "c-generic", campusId: "tamsui", buildingCode: "C", name: "鍾靈化學館教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["C 館"], clubUse: "fallback", note: "C + 樓層 + 室號。" },
  { id: "ed-generic", campusId: "tamsui", buildingCode: "ED", name: "教育大樓教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["ED 館"], clubUse: "fallback", note: "ED + 樓層 + 室號。" },
  { id: "g-generic", campusId: "tamsui", buildingCode: "G", name: "工學館教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["G 館"], clubUse: "fallback", note: "G + 樓層 + 室號。" },
  { id: "k-generic", campusId: "tamsui", buildingCode: "K", name: "建築系館教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["K 館"], clubUse: "fallback", note: "K + 樓層 + 室號。" },
  { id: "hc-generic", campusId: "tamsui", buildingCode: "HC", name: "守謙會議室", kind: "generic", venuePresetId: RECT, aliases: ["HC 館"], clubUse: "fallback", note: "未建檔的 HC 室號落到這裡。" },
  { id: "tku-generic", campusId: "tamsui", name: "淡江一般教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["淡江教室", "淡江教室模板"], clubUse: "fallback", note: "通用起點。" },
  { id: "taipei-generic", campusId: "taipei", buildingCode: "D", name: "臺北校園教室", kind: "generic", venuePresetId: RECT, aliases: ["臺北校園", "台北校園"], clubUse: "fallback", note: "D + 樓層 + 室號。" },
  { id: "lanyang-generic", campusId: "lanyang", buildingCode: "CL", name: "蘭陽校園教室", kind: "generic", venuePresetId: RECT, aliases: ["蘭陽", "蘭陽校園"], clubUse: "fallback", note: "以 CL 為主。" },
  { id: "i10-hall", campusId: "tamsui", buildingCode: "I", floor: 10, name: "覺生國際會議廳", kind: "hall", venuePresetId: RECT, aliases: ["覺生國際會議廳", "覺生國際廳"], clubUse: "fallback", publishedCapacity: 180, note: "綜大 10F。114 外借表 180 人。" },
  { id: "carrie-chang-hall", campusId: "tamsui", buildingCode: "T", floor: 2, name: "文\u932b音樂廳", kind: "hall", venuePresetId: RECT, aliases: ["文\u932b音樂廳", "文錙音樂廳", "文\u7e26音樂廳", "文縆音樂廳", "文\u9398音樂廳"], clubUse: "fallback", publishedCapacity: 252, note: "驚聲大樓 2F。外借系統最大容納 252 人。文\u932b藝術中心在松濤館。" },
  { id: "chung-ling-library", campusId: "tamsui", buildingCode: "C", name: "圖書館鍾靈分館", kind: "hall", venuePresetId: RECT, aliases: ["鍾靈分館"], clubUse: "fallback", note: "鍾靈化學館內。" },
  { id: "e-generic", campusId: "tamsui", buildingCode: "E", name: "工學大樓教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["E 館"], clubUse: "fallback", note: "未建檔的 E 室落到這裡。" },
  { id: "o-generic", campusId: "tamsui", buildingCode: "O", name: "傳播 O 館教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["O 館"], clubUse: "fallback", note: "傳播學院。" },
  { id: "q-generic", campusId: "tamsui", buildingCode: "Q", name: "傳播 Q 館教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["Q 館"], clubUse: "fallback", note: "前教育館。" },
  { id: "Q401", campusId: "tamsui", buildingCode: "Q", floor: 4, room: "01", name: "Q401 多功能空間", kind: "classroom", venuePresetId: CLASSROOM, aliases: ["Q401"], clubUse: "fallback", note: "大傳系公開空間。長寬未實測。" },
  { id: "Q403", campusId: "tamsui", buildingCode: "Q", floor: 4, room: "03", name: "Q403 會議室", kind: "hall", venuePresetId: RECT, aliases: ["Q403"], clubUse: "fallback", note: "大傳系可預約會議室。長寬未實測。" },
  { id: "xb-offices", campusId: "tamsui", buildingCode: "XB", name: "五虎崗新社辦", kind: "office", venuePresetId: CLASSROOM, aliases: ["新社辦", "XB"], clubUse: "fallback", note: "時報代號表曾列 XB。長寬未實測。" },
  { id: "natatorium", campusId: "tamsui", buildingCode: "N", name: "紹\u8b03紀念游泳館", kind: "hall", venuePresetId: RECT, aliases: ["游泳館", "紹\u8b03紀念游泳館", "紹謃紀念游泳館"], clubUse: "fallback", note: "公開運動場館。長寬未實測。" },
  { id: "white-hall", campusId: "tamsui", buildingCode: "DR", name: "白樓", kind: "hall", venuePresetId: RECT, aliases: ["白樓"], clubUse: "fallback", note: "地標建築。" },
  { id: "reitaku", campusId: "tamsui", buildingCode: "J", name: "麗澤國際學舍", kind: "hall", venuePresetId: RECT, aliases: ["麗澤"], clubUse: "fallback", note: "國際學生宿舍。" },
  { id: "international-hall", campusId: "tamsui", buildingCode: "ZF", name: "淡江國際學園", kind: "hall", venuePresetId: RECT, aliases: ["國際學園"], clubUse: "fallback", note: "宿舍／國際學園。" },
  { id: "flower-wall", campusId: "tamsui", name: "淡江大學花牆", kind: "outdoor", venuePresetId: BOOTH, aliases: ["花牆"], clubUse: "outdoor", note: "學府路與水源街口。徐維志設計。" },
  { id: "sanhua-wall", campusId: "tamsui", name: "三化牆", kind: "outdoor", venuePresetId: BOOTH, aliases: ["三化牆"], clubUse: "outdoor", note: "克難坡頂。國際化、資訊化、未來化。" },
  { id: "earth-village", campusId: "tamsui", buildingCode: "N", name: "地球村雕塑", kind: "outdoor", venuePresetId: BOOTH, aliases: ["地球村"], clubUse: "outdoor", note: "游泳館前。楊英風 1991。淡江十景。" },
  { id: "golden-eagle", campusId: "tamsui", buildingCode: "B", name: "金鷹銅雕", kind: "outdoor", venuePresetId: BOOTH, aliases: ["金鷹銅雕"], clubUse: "outdoor", note: "福園內。淡江十景。" },
  { id: "snow-tunnel", campusId: "lanyang", name: "雪山隧道雕塑", kind: "outdoor", venuePresetId: BOOTH, aliases: ["雪山隧道雕塑"], clubUse: "outdoor", note: "蘭陽校園。楊英風／胡澤民。淡江十景。" },
  { id: "culture-rest", campusId: "tamsui", buildingCode: "L", name: "文化休憩區", kind: "outdoor", venuePresetId: BOOTH, aliases: ["文化休憩區"], clubUse: "outdoor", note: "文學館、會文館、傳播館之間。時報公開名稱。" },
  { id: "poster-street", campusId: "tamsui", name: "海報街走廊", kind: "outdoor", venuePresetId: BOOTH, aliases: ["海報街"], clubUse: "outdoor", note: "走廊海報／臨時攤位起點。" },
  { id: "five-tiger-slope", campusId: "tamsui", buildingCode: "X", name: "五虎坡", kind: "outdoor", venuePresetId: BOOTH, aliases: ["五虎坡"], clubUse: "outdoor", note: "64 階，通往五虎碑。" },
  { id: "admin-generic", campusId: "tamsui", buildingCode: "A", name: "行政大樓", kind: "generic", venuePresetId: CLASSROOM, aliases: ["A 館"], clubUse: "fallback", note: "A + 樓層 + 室號。" },
  { id: "hwei-wen", campusId: "tamsui", buildingCode: "F", name: "會文館教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["會文館", "F 館"], clubUse: "fallback", note: "F + 樓層 + 室號。" },
  { id: "av-building", campusId: "tamsui", buildingCode: "V", name: "視聽教育館", kind: "generic", venuePresetId: CLASSROOM, aliases: ["視聽教育館", "V 館"], clubUse: "fallback", note: "V + 樓層 + 室號。" },
  { id: "wind-tunnel", campusId: "tamsui", buildingCode: "W", name: "風洞實驗室", kind: "hall", venuePresetId: RECT, aliases: ["風洞"], clubUse: "fallback", note: "工學院實驗空間。長寬未實測。" },
  { id: "sg-generic", campusId: "tamsui", buildingCode: "SG", name: "體育館教室", kind: "generic", venuePresetId: CLASSROOM, aliases: ["SG 館"], clubUse: "fallback", note: "未建檔的 SG 室落到這裡。" },
  { id: "h-generic", campusId: "tamsui", buildingCode: "H", name: "宮燈教室通用", kind: "generic", venuePresetId: CLASSROOM, aliases: ["H 館"], clubUse: "fallback", note: "H + 樓層 + 室號。" },
  { id: "sg1-generic", campusId: "tamsui", buildingCode: "SG", floor: 1, name: "SG1 社團辦公室層", kind: "generic", venuePresetId: CLASSROOM, aliases: ["SG1"], clubUse: "fallback", note: "1F 社辦層通用起點。" },
  { id: "library-study", campusId: "tamsui", buildingCode: "U", floor: 1, name: "圖書館自習室", kind: "hall", venuePresetId: RECT, aliases: ["圖書館自習室"], clubUse: "fallback", note: "總館公開樓層用途。長寬未實測。" },
  { id: "chueh-hsuan-house", campusId: "tamsui", buildingCode: "CH", name: "覺軒會館", kind: "hall", venuePresetId: RECT, aliases: ["覺軒會館"], clubUse: "fallback", note: "宮燈教室旁仿宋代庭園會館。" },
  { id: "f100-sabre", campusId: "tamsui", buildingCode: "M", name: "F-100 超級軍刀戰鬥機", kind: "outdoor", venuePresetId: BOOTH, aliases: ["軍刀戰鬥機", "F-100戰鬥機", "F-100"], clubUse: "outdoor", note: "海事博物館旁展示機。戶外地標，不是場地尺寸。" },
  { id: "lanyang-slope", campusId: "lanyang", name: "蘭陽克難坡", kind: "outdoor", venuePresetId: BOOTH, aliases: ["蘭陽克難坡"], clubUse: "outdoor", note: "蘭陽校園入口坡道。時報曾寫 132 階。戶外起點。" },
  { id: "turtle-island-view", campusId: "lanyang", name: "龜山日出", kind: "outdoor", venuePresetId: BOOTH, aliases: ["龜山日出", "龜山島"], clubUse: "outdoor", note: "蘭陽校園遠眺龜山島。觀景點，不是場地尺寸。" },
  { id: "chien-hsuan", campusId: "lanyang", buildingCode: "LX", name: "建軒一館", kind: "hall", venuePresetId: RECT, aliases: ["建軒", "建軒一館"], clubUse: "fallback", note: "蘭陽男生宿舍。目錄代號 LX，不是課表代碼。" },
  { id: "wen-yuan", campusId: "lanyang", buildingCode: "LW", name: "文苑一館", kind: "hall", venuePresetId: RECT, aliases: ["文苑", "文苑一館"], clubUse: "fallback", note: "蘭陽女生宿舍。目錄代號 LW，不是課表代碼。" },
];
