/** Named places the app can open a plan from. Dimensions stay on VenuePreset. */
import type { TkuPlace } from "./tkuCampus";

export const TKU_PLACES: TkuPlace[] = [
  { id: "E308", campusId: "tamsui", buildingCode: "E", floor: 3, room: "08", name: "E308 工學大樓教室", kind: "classroom", venuePresetId: "venue:tku-e308", aliases: ["E308"], clubUse: "primary", mentionCount: 101, note: "禪學社文件提及最多的教室。" },
  { id: "E310", campusId: "tamsui", buildingCode: "E", floor: 3, room: "10", name: "E310 工學大樓教室", kind: "classroom", venuePresetId: "venue:tku-e310", aliases: ["E310"], clubUse: "frequent", mentionCount: 54, note: "Golden Venue。長寬仍未實測。" },
  { id: "E301", campusId: "tamsui", buildingCode: "E", floor: 3, room: "01", name: "E301 工學大樓教室", kind: "classroom", venuePresetId: "venue:tku-classroom", clubUse: "fallback", mentionCount: 4, note: "偶用。" },
  { id: "E311", campusId: "tamsui", buildingCode: "E", floor: 3, room: "11", name: "E311 工學大樓教室", kind: "classroom", venuePresetId: "venue:tku-classroom", clubUse: "fallback", mentionCount: 4, note: "偶用。" },
  { id: "SG109", campusId: "tamsui", buildingCode: "SG", floor: 1, room: "09", name: "SG109 社辦", kind: "office", venuePresetId: "venue:tku-sg109", aliases: ["社辦", "SG109"], clubUse: "office", mentionCount: 100, note: "集合／搬巧拼起點。" },
  { id: "SG320", campusId: "tamsui", buildingCode: "SG", floor: 3, room: "20", name: "SG320 體育館教室", kind: "classroom", venuePresetId: "venue:tku-sg320", aliases: ["SG320"], clubUse: "frequent", mentionCount: 27, note: "體育館教室。" },
  { id: "SG319", campusId: "tamsui", buildingCode: "SG", floor: 3, room: "19", name: "SG319 體育館教室", kind: "classroom", venuePresetId: "venue:tku-classroom", clubUse: "fallback", mentionCount: 4, note: "偶用。" },
  { id: "SG321", campusId: "tamsui", buildingCode: "SG", floor: 3, room: "21", name: "SG321 體育館教室", kind: "classroom", venuePresetId: "venue:tku-classroom", clubUse: "fallback", mentionCount: 4, note: "偶用。" },
  { id: "SG402", campusId: "tamsui", buildingCode: "SG", floor: 4, room: "02", name: "SG402 體育館教室", kind: "classroom", venuePresetId: "venue:tku-classroom", clubUse: "fallback", mentionCount: 13, note: "偶用。" },
  { id: "SG603", campusId: "tamsui", buildingCode: "SG", floor: 6, room: "03", name: "SG603 體育館教室", kind: "classroom", venuePresetId: "venue:tku-classroom", clubUse: "fallback", mentionCount: 4, note: "偶用。" },
  { id: "scroll-plaza", campusId: "tamsui", buildingCode: "T", name: "書卷廣場", kind: "plaza", venuePresetId: "venue:tku-plaza-scroll", aliases: ["書卷廣場", "蛋捲廣場"], clubUse: "outdoor", note: "驚聲大樓前。套用 3×3 帳篷起點。" },
  { id: "tongzhou-plaza", campusId: "tamsui", buildingCode: "I", floor: 1, name: "同舟廣場", kind: "plaza", venuePresetId: "venue:tku-booth", aliases: ["同舟廣場"], clubUse: "outdoor", note: "綜大 1F 中庭。" },
  { id: "hc-hall", campusId: "tamsui", buildingCode: "HC", name: "守謙國際會議中心", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["守謙"], clubUse: "fallback", note: "大型會議。" },
  { id: "palace-classroom", campusId: "tamsui", buildingCode: "H", name: "宮燈教室", kind: "classroom", venuePresetId: "venue:tku-classroom", aliases: ["宮燈"], clubUse: "fallback", note: "古跡教室。" },
  { id: "chueh-hsuan-garden", campusId: "tamsui", buildingCode: "CH", name: "覺軒花園", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["覺軒花園"], clubUse: "outdoor", note: "戶外茶會起點。" },
  { id: "library", campusId: "tamsui", buildingCode: "U", name: "覺生紀念圖書館", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["圖書館", "總館"], clubUse: "fallback", note: "九層總館。" },
  { id: "maritime-museum", campusId: "tamsui", buildingCode: "M", name: "海事博物館", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["海博"], clubUse: "fallback", note: "免費開放。" },
  { id: "history-museum", campusId: "tamsui", buildingCode: "TH", name: "校史館暨張建邦創辦人紀念館", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["校史館"], clubUse: "fallback", note: "舊瀛苑整修。" },
  { id: "activity-center", campusId: "tamsui", buildingCode: "R", name: "學生活動中心", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["活動中心"], clubUse: "fallback", note: "社團空間。" },
  { id: "sa-center", campusId: "lanyang", buildingCode: "SA", name: "紹謃紀念活動中心", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["紹謃活動中心"], clubUse: "fallback", note: "蘭陽，不是淡水 SG。" },
  { id: "sg7-hall", campusId: "tamsui", buildingCode: "SG", floor: 7, name: "SG7 體育館集會場", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["SG7"], clubUse: "fallback", note: "7F 集會場。" },
  { id: "sg4-court", campusId: "tamsui", buildingCode: "SG", floor: 4, name: "SG4 羽球／排球場", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["SG4"], clubUse: "fallback", note: "4F 球場。" },
  { id: "black-swan", campusId: "tamsui", name: "黑天鵝展示廳", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["黑天鵝"], clubUse: "fallback", note: "公開外借場地。" },
  { id: "ching-sheng-hall", campusId: "tamsui", buildingCode: "T", name: "驚聲國際會議廳", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["驚聲國際會議廳"], clubUse: "fallback", note: "驚聲大樓內。" },
  { id: "knan-slope", campusId: "tamsui", name: "克難坡", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["克難坡"], clubUse: "outdoor", note: "132 階，1953。" },
  { id: "ching-sheng-statue", campusId: "tamsui", buildingCode: "N", name: "驚聲銅像廣場", kind: "plaza", venuePresetId: "venue:tku-booth", aliases: ["驚聲銅像"], clubUse: "outdoor", note: "游泳館前方。" },
  { id: "fortune-garden", campusId: "tamsui", buildingCode: "B", name: "福園", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["福園"], clubUse: "outdoor", note: "商管大樓前。" },
  { id: "li-shuang-ze", campusId: "tamsui", name: "李雙澤紀念碑", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["李雙澤"], clubUse: "outdoor", note: "民歌紀念地。" },
  { id: "sheep-lawn", campusId: "tamsui", name: "牧羊草坪", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["牧羊草坪"], clubUse: "outdoor", note: "休憤草坪。" },
  { id: "dolphin-milestone", campusId: "tamsui", name: "海豚吉祥物里程碑", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["淡江海豚"], clubUse: "outdoor", note: "吉祥物地標。" },
  { id: "food-plaza", campusId: "tamsui", name: "美食廣場", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["美食廣場"], clubUse: "outdoor", note: "臨時攤位區。" },
  { id: "five-tiger-stele", campusId: "tamsui", buildingCode: "X", name: "五虎碑", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["五虎碑"], clubUse: "outdoor", note: "五虎崗地標。" },
  { id: "lanyang-hall", campusId: "lanyang", buildingCode: "LH", name: "建邦國際會議廳", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["建邦國際廳"], clubUse: "fallback", publishedCapacity: 286, note: "外借表 286 人。" },
  { id: "CL408", campusId: "lanyang", buildingCode: "CL", floor: 4, room: "08", name: "CL408 會議室", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["CL408"], clubUse: "fallback", note: "蘭陽外借表。" },
  { id: "CL426", campusId: "lanyang", buildingCode: "CL", floor: 4, room: "26", name: "CL426 會議室", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["CL426"], clubUse: "fallback", note: "蘭陽外借表。" },
  { id: "CL506", campusId: "lanyang", buildingCode: "CL", floor: 5, room: "06", name: "CL506 會議室", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["CL506"], clubUse: "fallback", note: "蘭陽外借表。" },
  { id: "D207", campusId: "taipei", buildingCode: "D", floor: 2, room: "07", name: "D207 階梯教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 120, note: "外借表 120 人。" },
  { id: "D208", campusId: "taipei", buildingCode: "D", floor: 2, room: "08", name: "D208 階梯教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 120, note: "外借表 120 人。" },
  { id: "D211", campusId: "taipei", buildingCode: "D", floor: 2, room: "11", name: "D211 多媒體教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 81, note: "外借表 81 人。" },
  { id: "D304", campusId: "taipei", buildingCode: "D", floor: 3, room: "04", name: "D304 電腦教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 48, note: "外借表 48 人。" },
  { id: "D305", campusId: "taipei", buildingCode: "D", floor: 3, room: "05", name: "D305 電腦教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 40, note: "外借表 40 人。" },
  { id: "D309", campusId: "taipei", buildingCode: "D", floor: 3, room: "09", name: "D309 個案教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 54, note: "外借表 54 人。" },
  { id: "D310", campusId: "taipei", buildingCode: "D", floor: 3, room: "10", name: "D310 個案教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 50, note: "外借表 50 人。" },
  { id: "D510", campusId: "taipei", buildingCode: "D", floor: 5, room: "10", name: "D510 個案教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 50, note: "外借表 50 人。" },
  { id: "D318", campusId: "taipei", buildingCode: "D", floor: 3, room: "18", name: "D318 多媒體教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 81, note: "外借表 81 人。" },
  { id: "D401", campusId: "taipei", buildingCode: "D", floor: 4, room: "01", name: "D401 多媒體教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 90, note: "外借表 90 人。" },
  { id: "D408", campusId: "taipei", buildingCode: "D", floor: 4, room: "08", name: "D408 多媒體教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 81, note: "外借表 81 人。" },
  { id: "D501", campusId: "taipei", buildingCode: "D", floor: 5, room: "01", name: "D501 多媒體教室", kind: "classroom", venuePresetId: "venue:rect-classroom", publishedCapacity: 90, note: "外借表 90 人。" },
  { id: "D509", campusId: "taipei", buildingCode: "D", floor: 5, room: "09", name: "D509 會議室", kind: "hall", venuePresetId: "venue:rect-classroom", publishedCapacity: 64, note: "外借表 64 人。" },
  { id: "reviewing-stand", campusId: "tamsui", buildingCode: "P", name: "操場司令臺", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["司令臺", "操場"], clubUse: "outdoor", note: "操場集合。" },
  { id: "blue-white-town", campusId: "tamsui", buildingCode: "GB", name: "藍白小鎮", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["藍白小鎮"], clubUse: "outdoor", note: "餐飲休憤區。" },
  { id: "wuhugang-court", campusId: "tamsui", buildingCode: "XC", name: "五虎崗綜合球場", kind: "outdoor", venuePresetId: "venue:tku-booth", aliases: ["綜合球場"], clubUse: "outdoor", note: "戶外球場。" },
  { id: "sung-tao", campusId: "tamsui", buildingCode: "Z", name: "松濤館／文鎘藝術中心", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["松濤館", "文鎘"], clubUse: "fallback", note: "展演空間。" },
  { id: "b-generic", campusId: "tamsui", buildingCode: "B", name: "商管大樓教室", kind: "generic", venuePresetId: "venue:tku-classroom", aliases: ["B 館"], clubUse: "fallback", note: "例如 B616。" },
  { id: "l-generic", campusId: "tamsui", buildingCode: "L", name: "文學館教室", kind: "generic", venuePresetId: "venue:tku-classroom", aliases: ["L 館"], clubUse: "fallback", note: "例如 L201。" },
  { id: "fl-generic", campusId: "tamsui", buildingCode: "FL", name: "外語大樓教室", kind: "generic", venuePresetId: "venue:tku-classroom", aliases: ["FL"], clubUse: "fallback", note: "FL + 樓層 + 室號。" },
  { id: "t-generic", campusId: "tamsui", buildingCode: "T", name: "驚聲大樓教室", kind: "generic", venuePresetId: "venue:tku-classroom", aliases: ["T 館"], clubUse: "fallback", note: "書卷廣場在前。" },
  { id: "i-generic", campusId: "tamsui", buildingCode: "I", name: "綜大教室", kind: "generic", venuePresetId: "venue:tku-classroom", aliases: ["I 館"], clubUse: "fallback", note: "同舟廣場在 1F。" },
  { id: "s-generic", campusId: "tamsui", buildingCode: "S", name: "科學館教室", kind: "generic", venuePresetId: "venue:tku-classroom", aliases: ["科館"], clubUse: "fallback", note: "騮先紀念科學館。" },
  { id: "tku-generic", campusId: "tamsui", name: "淡江一般教室", kind: "generic", venuePresetId: "venue:tku-classroom", aliases: ["淡江教室", "淡江教室模板"], clubUse: "fallback", note: "通用起點。" },
  { id: "taipei-generic", campusId: "taipei", buildingCode: "D", name: "臺北校園教室", kind: "generic", venuePresetId: "venue:rect-classroom", aliases: ["臺北校園", "台北校園"], clubUse: "fallback", note: "D + 樓層 + 室號。" },
  { id: "lanyang-generic", campusId: "lanyang", buildingCode: "CL", name: "蘭陽校園教室", kind: "generic", venuePresetId: "venue:rect-classroom", aliases: ["蘭陽", "蘭陽校園"], clubUse: "fallback", note: "以 CL 為主。" },
  { id: "i10-hall", campusId: "tamsui", buildingCode: "I", floor: 10, name: "覺生國際會議廳", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["覺生國際會議廳"], clubUse: "fallback", note: "綜大 10F。" },
  { id: "carrie-chang-hall", campusId: "tamsui", buildingCode: "Z", name: "文鎘音樂廳", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["文鎘音樂廳"], clubUse: "fallback", note: "松濤館／文鎘。" },
  { id: "chung-ling-library", campusId: "tamsui", buildingCode: "C", name: "圖書館鍾靈分館", kind: "hall", venuePresetId: "venue:rect-classroom", aliases: ["鍾靈分館"], clubUse: "fallback", note: "鍾靈化學館內。" },
];
