import "./style.css";
import { SceneManager, type ViewName } from "./scene/SceneManager";
import { DEFAULT_TILE } from "./core/room";
import { metersToCm } from "./core/units";

const canvas = document.getElementById("scene");
if (!(canvas instanceof HTMLCanvasElement)) {
  throw new Error("#scene canvas not found");
}

const manager = new SceneManager(canvas);

// Camera view buttons — camera changes never alter scene data.
const viewButtons = Array.from(
  document.querySelectorAll<HTMLButtonElement>("[data-view]"),
);
for (const button of viewButtons) {
  button.addEventListener("click", () => {
    const view = button.dataset.view as ViewName;
    manager.setView(view);
    for (const other of viewButtons) {
      other.setAttribute("aria-pressed", String(other === button));
    }
  });
}

// Grid toggle.
const gridButton = document.getElementById("toggle-grid");
if (gridButton instanceof HTMLButtonElement) {
  gridButton.addEventListener("click", () => {
    const next = gridButton.getAttribute("aria-pressed") !== "true";
    gridButton.setAttribute("aria-pressed", String(next));
    manager.setGridVisible(next);
  });
}

// PNG export.
const exportButton = document.getElementById("export-png");
if (exportButton instanceof HTMLButtonElement) {
  exportButton.addEventListener("click", () => {
    const url = manager.exportPng();
    const link = document.createElement("a");
    link.href = url;
    link.download = "planform-iso.png";
    link.click();
  });
}

// Readouts.
const tileReadout = document.getElementById("tile-readout");
if (tileReadout) {
  const w = metersToCm(DEFAULT_TILE.width);
  const d = metersToCm(DEFAULT_TILE.depth);
  tileReadout.textContent = `格 ${w} × ${d} cm`;
}

// Register the service worker generated by vite-plugin-pwa (production only).
if ("serviceWorker" in navigator && import.meta.env.PROD) {
  window.addEventListener("load", () => {
    void navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`);
  });
}
